### ISSUE TITLE
packagist.org

### ISSUE THREAD

**Issue by varvashenya** [mhrabovcin/zuora-rest#4]
Packagist.org still has old version of the library - dev-master 2016-07-13 16:14 UTC
@mhrabovcin do you have a power to force packagist to pull shiny new version?
https://packagist.org/packages/mhrabovcin/zuora-rest

Thanks.

**Comment by mhrabovcin** [comment]
It should be updated now @varvashenya, thanks!

**Comment by hopeseekr** [comment]
When I sttarted my own Zuora-API-Client back in January 2019, this sure wasn't there. I looked.

I'm giving you a run for your money in terms of usability, tho.
